### ISSUE TITLE
Runtimeerror: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by SAWRJJ** [LiamLian0727/WaterMask#1]
Thank you for the excellent model and data set you provided. I have a question to ask you now. When I try to train water_r50_fpn_ms3x.py or set 'samples_per_gpu == 1' for training, an error will occur which is Runtimeerror: torch.cat(): expected a non-empty list of Tensors. Have you encountered the same problem during training and how did you solve it?

**Comment by LiamLian0727** [comment]
I'm glad you're interested in our work.
Although I haven't encountered the problem you mentioned in training, I think it's possible that an empty list was entered into torch.cat() at some point, e.g. the model didn't predict any labels in one of the early training batch, causing it to produce an empty list!
Maybe you can fix the bug by setting 'samples_per_gpu == 2' or by adding a simple check before torch.cat in the code that report the error. 
If you can provide more error logs, maybe I can help you solve the problem better!

**Comment by SAWRJJ** [comment]
> I'm glad you're interested in our work. Although I haven't encountered the problem you mentioned in training, I think it's possible that an empty list was entered into torch.cat() at some point, e.g. the model didn't predict any labels in one of the early training batch, causing it to produce an empty list! Maybe you can fix the bug by setting 'samples_per_gpu == 2' or by adding a simple check before torch.cat in the code that report the error. If you can provide more error logs, maybe I can help you solve the problem better!

Traceback (most recent call last):
  File "D:/PythonV6/WaterMask-master/tools/train.py", line 243, in <module>
    main()
  File "D:/PythonV6/WaterMask-master/tools/train.py", line 239, in main
    meta=meta)
  File "D:\PythonV6\WaterMask-master\mmdet\apis\train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "D:\Anaconda3\envs\mms\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "D:\Anaconda3\envs\mms\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "D:\Anaconda3\envs\mms\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 32, in run_iter
    **kwargs)
  File "D:\Anaconda3\envs\mms\lib\site-packages\mmcv\parallel\data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "D:\PythonV6\WaterMask-master\mmdet\models\detectors\base.py", line 248, in train_step
    losses = self(**data)
  File "D:\Anaconda3\envs\mms\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda3\envs\mms\lib\site-packages\mmcv\runner\fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "D:\PythonV6\WaterMask-master\mmdet\models\detectors\base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "D:\PythonV6\WaterMask-master\mmdet\models\detectors\two_stage.py", line 150, in forward_train
    **kwargs)
  File "D:\PythonV6\WaterMask-master\mmdet\models\roi_heads\standard_roi_head.py", line 113, in forward_train
    gt_masks, img_metas)
  File "D:\PythonV6\WaterMask-master\mmdet\models\roi_heads\water_roi_head.py", line 40, in _mask_forward_train
    mask_results = self._mask_forward(x, pos_rois, torch.cat(pos_labels))
  File "D:\PythonV6\WaterMask-master\mmdet\models\roi_heads\water_roi_head.py", line 51, in _mask_forward
    stage_lcf_preds = self.mask_head(ins_feats, x[0], rois, roi_labels)
  File "D:\Anaconda3\envs\mms\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PythonV6\WaterMask-master\mmdet\models\roi_heads\mask_heads\water_mask_head.py", line 324, in forward
    lcf_feats, lcf_logits, gff_feat, rois, upsample_flag)
  File "D:\Anaconda3\envs\mms\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PythonV6\WaterMask-master\mmdet\models\roi_heads\mask_heads\water_mask_head.py", line 188, in forward
    ins_gff_feats = self.gff_roi_extractor(gff_feat, rois)
  File "D:\Anaconda3\envs\mms\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda3\envs\mms\lib\site-packages\mmcv\ops\point_sample.py", line 349, in forward
    point_feats = torch.cat(point_feats, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

        if torch.onnx.is_in_onnx_export():
            rel_img_points = rel_roi_point_to_rel_img_point(
                rois, rel_roi_points, features, self.spatial_scale)
            rel_img_points = rel_img_points.reshape(num_imgs, -1,
                                                    *rel_img_points.shape[1:])
            point_feats = point_sample(
                features, rel_img_points, align_corners=not self.aligned)
            point_feats = point_feats.transpose(1, 2)
        else:
            point_feats = []
            for batch_ind in range(num_imgs):
                # unravel batch dim
                feat = features[batch_ind].unsqueeze(0)
                inds = (rois[:, 0].long() == batch_ind)
                if inds.any():
                    rel_img_points = rel_roi_point_to_rel_img_point(
                        rois[inds], rel_roi_points[inds], feat,
                        self.spatial_scale).unsqueeze(0)
                    point_feat = point_sample(
                        feat, rel_img_points, align_corners=not self.aligned)
                    point_feat = point_feat.squeeze(0).transpose(0, 1)
                    point_feats.append(point_feat)

            point_feats = torch.cat(point_feats, dim=0)
These are the error code in point_sample.py

**Comment by LiamLian0727** [comment]
Maybe you can try to initialize your own weights with the pre-trained model we posted, which might help you circumvent this problem

**Comment by SAWRJJ** [comment]
> Maybe you can try to initialize your own weights with the pre-trained model we posted, which might help you circumvent this problem

base-248 {'img_metas': [{'filename': 'data/UDW/train/XL_2059.jpg', 'ori_filename': 'XL_2059.jpg', 'ori_shape': (480, 640, 3), 'img_shape': (800, 1067, 3), 'pad_shape': (800, 1088, 3), 'scale_factor': array([1.6671875, 1.6666666, 1.6671875, 1.6666666], dtype=float32), 'flip': False, 'flip_direction': None, 'img_norm_cfg': {'mean': array([ 81.236, 113.761, 117.095], dtype=float32), 'std': array([60.598, 58.471, 62.821], dtype=float32), 'to_rgb': True}}], 'img': tensor([[[[-1.1921, -1.1921, -1.1756,  ...,  0.0000,  0.0000,  0.0000],
          [-1.1756, -1.1756, -1.1590,  ...,  0.0000,  0.0000,  0.0000],
          [-1.1425, -1.1425, -1.1425,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.1116,  0.1611,  0.2271,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.1116,  0.1611,  0.2271,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.1116,  0.1611,  0.2271,  ...,  0.0000,  0.0000,  0.0000]],

         [[-1.4154, -1.4154, -1.3983,  ...,  0.0000,  0.0000,  0.0000],
          [-1.3812, -1.3812, -1.3812,  ...,  0.0000,  0.0000,  0.0000],
          [-1.3299, -1.3299, -1.3299,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [-0.2524, -0.2011, -0.1327,  ...,  0.0000,  0.0000,  0.0000],
          [-0.2524, -0.2011, -0.1327,  ...,  0.0000,  0.0000,  0.0000],
          [-0.2524, -0.2011, -0.1327,  ...,  0.0000,  0.0000,  0.0000]],

         [[-1.1635, -1.1635, -1.1476,  ...,  0.0000,  0.0000,  0.0000],
          [-1.1476, -1.1317, -1.1317,  ...,  0.0000,  0.0000,  0.0000],
          [-1.0999, -1.0999, -1.0999,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [-0.7656, -0.7178, -0.6542,  ...,  0.0000,  0.0000,  0.0000],
          [-0.7656, -0.7178, -0.6542,  ...,  0.0000,  0.0000,  0.0000],
          [-0.7656, -0.7178, -0.6542,  ...,  0.0000,  0.0000,  0.0000]]]],
       device='cuda:0'), 'gt_bboxes': [tensor([], device='cuda:0', size=(0, 4))], 'gt_labels': [tensor([], device='cuda:0', dtype=torch.int64)], 'gt_masks': [BitmapMasks(num_masks=0, height=800, width=1088)]}
I get the above result when I try to output the error message, and I don't understand why the gt_boxes and gt_labels of the data are not detected

**Comment by LiamLian0727** [comment]
I can't reproduce your problem, I ran my code again and everything works fine. At which step did you get the img_metas, maybe you can check in the _mask_forward_train() and _mask_forward() functions (in water_roi_head.py) on whether the model gets the roi and roi label correctly!

**Comment by LiamLian0727** [comment]
This problem is due to a combination of the following three scenarios
1: set samples_per_gpu == 1 in single gpu, i.e. batch_size=1
2: the iscrowd= 1 of this instance in the dataset , and mmdetection will not add the gt with iscrowd = 1 to pos_assigned_gt by default, i.e., add_gt_as_proposals=True in the mmdet configuration fails at this time
3: The model did not infer any pos_boxes for this instance in the early stages of training.
Therefore, the final roi list is empty

**Comment by SAWRJJ** [comment]
I figure out where is the problem, there are some images' annotations have wrong or just themselves. I list them out here.
data/UDW/train/L_901.jpg
data/UDW/train/XL_1919.jpg
data/UDW/train/XL_1926.jpg
data/UDW/train/XL_1949.jpg
data/UDW/train/XL_1950.jpg
data/UDW/train/XL_2059.jpg
data/UDW/train/XL_284.jpg
data/UDW/train/XL_2933.jpg
data/UDW/train/XL_752.jpg
data/UDW/train/XL_856.jpg
when I deleted them, the probelm has been also solved.

**Comment by LiamLian0727** [comment]
Thank you for your contribution and if you feel our work and datasets are useful, please cite us!

**Comment by likaiw2** [comment]
> I figure out where is the problem, there are some images' annotations have wrong or just themselves. I list them out here. data/UDW/train/L_901.jpg data/UDW/train/XL_1919.jpg data/UDW/train/XL_1926.jpg data/UDW/train/XL_1949.jpg data/UDW/train/XL_1950.jpg data/UDW/train/XL_2059.jpg data/UDW/train/XL_284.jpg data/UDW/train/XL_2933.jpg data/UDW/train/XL_752.jpg data/UDW/train/XL_856.jpg when I deleted them, the probelm has been also solved.

Hi, I had the same problem.

After I delete those files, it reports that "no such file or dictionary", shall I delete them in the Json file, either?

**Comment by SAWRJJ** [comment]
Yes, you need to totally delete these images' information.

likaiw2 ***@***.***> 于2024年9月19日周四 09:43写道：

**Comment by likaiw2** [comment]
What's the difference between "id" and "image_id" in the json file, are they the same?

<img width="655" alt="image" src="https://github.com/user-attachments/assets/2ad73eb7-d79f-43f3-880d-a0c537f14646">

**Comment by SAWRJJ** [comment]
I can't remember the exact details, you can check to see if it's the same
by outputting it via key

likaiw2 ***@***.***> 于2024年9月19日周四 10:02写道：

**Comment by likaiw2** [comment]
Okay, thank you very much. :)

**Comment by SAWRJJ** [comment]
Sure, no problem.

likaiw2 ***@***.***> 于2024年9月19日周四 10:13写道：
