### ISSUE TITLE
代码请求

### ISSUE THREAD

**Issue by akang-ai** [LiamLian0727/WaterMask#11]
我使用了我自己制作的数据集，但训练的时候老是报这样的错误，请问该怎么解决？
![image](https://github.com/user-attachments/assets/88d293f0-5a1a-4a6a-84ab-eba77241dcb2)

**Comment by LiamLian0727** [comment]
The code shows that the dataset must contain the key `flag`, please check that the dataset category in your mmdetection configuration is `CocoDataset` and that you are using the correct profile format.
For the annotation format of the ms coco dataset, please refer to [this](https://cocodataset.org/#format-data).

**Comment by akang-ai** [comment]
[train.json](https://github.com/user-attachments/files/17831416/train.json)
这是我自制数据集的一小部分，使用你之前跟我说的labelme制作而成，然后用脚本把它转成coco数据集的形式，这个跟你所提供的数据集基本一样了，请你帮我看看还有哪里有错？万分感谢

**Comment by LiamLian0727** [comment]
you can refer to https://github.com/open-mmlab/mmtracking/issues/358 ， https://github.com/open-mmlab/mmdetection/issues/1152 and https://github.com/open-mmlab/mmdetection/issues/72 . Hope this helps you.

**Comment by LiamLian0727** [comment]
In addition, OpenMMLab has published a blog on this part of the code for a detailed description, see [this](https://zhuanlan.zhihu.com/p/166102368).
