### ISSUE TITLE
Difference Similarity Graph Attention Module，DSGAT

### ISSUE THREAD

**Issue by zhouyuchen0** [LiamLian0727/WaterMask#12]
I would like to ask the author about your Difference Similarity Graph Attention Module (DSGAT) in that py file, looking forward to your reply thanks!

**Comment by LiamLian0727** [comment]
Begin in [this](https://github.com/LiamLian0727/WaterMask/blob/master/mmdet/models/roi_heads/mask_heads/water_mask_head.py#L15) (Line 15),  feel free to cite us if this helps!
