### ISSUE TITLE
Boundary Mask Strategy

### ISSUE THREAD

**Issue by liuxinyi-sys** [LiamLian0727/WaterMask#9]
请问论文中提到的边界掩码策略在代码中的哪一部分？我该在哪里找到它

**Comment by LiamLian0727** [comment]
The code about BMS is in [cross_entropy_loss.py](https://github.com/LiamLian0727/WaterMask/blob/master/mmdet/models/losses/cross_entropy_loss.py#L323) and [water_mask_head.py](https://github.com/LiamLian0727/WaterMask/blob/master/mmdet/models/roi_heads/mask_heads/water_mask_head.py).
If you find our code useful, please cite us in your paper!
```
@InProceedings{Lian_2023_ICCV,
    author    = {Lian, Shijie and Li, Hua and Cong, Runmin and Li, Suqi and Zhang, Wei and Kwong, Sam},
    title     = {WaterMask: Instance Segmentation for Underwater Imagery},
    booktitle = {Proceedings of the IEEE/CVF International Conference on Computer Vision (ICCV)},
    month     = {October},
    year      = {2023},
    pages     = {1305-1315}
}
```
